spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: java-eai-shipment

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: eai-shipment-api
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": com.eaishipment.shipment.event

  datasource:
    url: jdbc:h2:file:D:/h2/eai-shipment-api/shipmentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true

security:
  api-key:
    header-name: X-API-KEY
    value: ${EAI_API_KEY:local-dev-api-key}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

shipment:
  dispatch:
    scheduler:
      cron: 
        default: "0 */5 * * * *"
    timeout-minutes: 10

    